name: network
description: "A local package for managing network calls, interceptors, and exception translation."
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.2
  meta: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
