import os
import json

en_errors = {
    "unknown": "An unexpected error occurred. Please try again.",
    "unauthorized": "Session expired. Please log in again.",
    "validation_error": "Invalid inputs. Please check your data.",
    "password_incorrect": "Incorrect password. Please try again.",
    "account_not_found": "Account not found.",
    "email_template_already_exists": "Email template already exists.",
    "email_template_not_found": "Email template not found.",
    "account_email_limit_register": "Registration limit reached for this email.",
    "account_username_is_exist": "Username is already taken.",
    "token_invalid": "Invalid session token. Please log in again.",
    "already_enable_2fa": "Two-factor authentication is already enabled.",
    "account_are_not_enable_2fa": "Two-factor authentication is not enabled.",
    "ref_account_not_found": "Referral account not found.",
    "account_already_vip": "Account is already VIP.",
    "perm_not_found": "Permission not found.",
    "account_register_not_found": "Registration details not found.",
    "otp_invalid": "Invalid OTP code. Please check and try again.",
    "otp_expired": "OTP code has expired. Please request a new one.",
    "otp_to_many_request": "Too many requests. Please wait before trying again.",
    "account_info_not_found": "Account information not found.",
    "account_info_already_created": "Account information is already created.",
    "id_number_already_in_use": "ID number is already in use.",
    "account_info_can_not_update": "Account information cannot be updated.",
    "account_profile_is_processed": "Account profile is currently being processed.",
    "insufficient_fund": "Insufficient funds or credits.",
    "account_email_is_exist": "Email is already registered.",
    "proxy_error": "Proxy connection error.",
    "invalid_file_type": "Invalid file type. Please use supported formats.",
    "file_too_large": "File size exceeds the 20MB limit.",
    "account_banned": "Your account has been banned.",
    "login_failed": "Login failed. Please check your credentials.",
    "error_code": "An error occurred with code validation.",
    "user_not_found": "User not found.",
    "user_used_invite_code": "Invite code has already been used.",
    "get_me_failed": "Failed to retrieve user profile.",
    "user_cannot_use_own_invite_code": "You cannot use your own invite code.",
    "file_not_found": "File not found.",
    "file_upload_failed": "Failed to upload file. Please try again.",
    "upload_webp_failed": "Failed to upload WEBP file.",
    "create_theme_failed": "Failed to create theme.",
    "get_theme_failed": "Failed to retrieve themes.",
    "category_already_exists": "Category already exists.",
    "create_category_failed": "Failed to create category.",
    "invalid_ratio": "Invalid video ratio.",
    "create_media_failed": "Failed to initiate video generation.",
    "media_not_found": "Video or image file not found.",
    "callback_media_failed": "Callback media processing failed.",
    "get_media_detail_failed": "Failed to retrieve video details.",
    "get_media_failed": "Failed to retrieve media list.",
    "update_theme_failed": "Failed to update theme.",
    "delete_theme_failed": "Failed to delete theme.",
    "category_not_found": "Category not found.",
    "delete_category_failed": "Failed to delete category.",
    "media_not_owned": "You do not own this media.",
    "theme_already_exists": "Theme already exists.",
    "like_media_failed": "Failed to update like status.",
    "user_not_vip": "This feature requires a VIP subscription.",
    "not_enough_credit": "Not enough credits. Please purchase more credits.",
    "create_photo_enhance_failed": "Photo enhancement failed.",
    "remove_object_failed": "Failed to remove object from photo.",
    "get_suggestion_prompt_failed": "Failed to suggest prompt.",
    "get_tasks_failed": "Failed to load tasks.",
    "action_task_failed": "Failed to perform task action.",
    "task_not_found": "Task not found.",
    "task_already_claimed": "Task reward already claimed.",
    "task_already_started": "Task has already been started.",
    "task_not_completed": "Task is not completed yet.",
    "rate_app_failed": "Rating app failed.",
    "daily_login_task_not_found": "Daily login task not found.",
    "get_daily_login_failed": "Failed to get daily login task.",
    "today_login_reward_already_claimed": "Today's reward already claimed.",
    "take_login_reward_failed": "Failed to claim login reward.",
    "iap_receipt_already_exists": "Purchase receipt already registered.",
    "iap_verify_product_failed": "Failed to verify purchase product.",
    "iap_product_not_purchased": "Product is not purchased.",
    "iap_product_not_found": "In-app purchase product not found.",
    "iap_subscription_not_active": "Subscription is not active.",
    "iap_subscription_already_acknowledged": "Subscription already acknowledged.",
    "iap_verify_subscription_failed": "Failed to verify subscription.",
    "refill_subscription_credits_failed": "Failed to refill subscription credits.",
    "cancel_subscription_failed": "Failed to cancel subscription.",
    "plan_not_found": "Subscription plan not found.",
    "transaction_action_failed": "Transaction action failed.",
    "iap_verify_ios_product_failed": "Failed to verify iOS purchase.",
    "iap_subscription_invalid_type": "Invalid subscription type.",
    "subscription_not_active_for_refill": "Subscription is not active for credit refill.",
    "get_price_list_failed": "Failed to retrieve credit price list.",
    "iap_receipt_not_found": "Purchase receipt not found.",
    "iap_subscription_not_found": "Subscription not found."
}

vi_errors = {
    "unknown": "Đã xảy ra lỗi không xác định. Vui lòng thử lại sau.",
    "unauthorized": "Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.",
    "validation_error": "Thông tin không hợp lệ. Vui lòng kiểm tra lại.",
    "password_incorrect": "Mật khẩu không chính xác. Vui lòng thử lại.",
    "account_not_found": "Không tìm thấy tài khoản.",
    "email_template_already_exists": "Mẫu email đã tồn tại.",
    "email_template_not_found": "Không tìm thấy mẫu email.",
    "account_email_limit_register": "Email này đã đạt giới hạn đăng ký.",
    "account_username_is_exist": "Tên đăng nhập đã được sử dụng.",
    "token_invalid": "Phiên làm việc không hợp lệ. Vui lòng đăng nhập lại.",
    "already_enable_2fa": "Bảo mật 2 lớp đã được bật.",
    "account_are_not_enable_2fa": "Tài khoản chưa bật bảo mật 2 lớp.",
    "ref_account_not_found": "Không tìm thấy tài khoản người giới thiệu.",
    "account_already_vip": "Tài khoản đã là VIP.",
    "perm_not_found": "Không tìm thấy quyền hạn.",
    "account_register_not_found": "Không tìm thấy thông tin đăng ký.",
    "otp_invalid": "Mã OTP không hợp lệ. Vui lòng kiểm tra lại.",
    "otp_expired": "Mã OTP đã hết hạn. Vui lòng yêu cầu mã mới.",
    "otp_to_many_request": "Quá nhiều yêu cầu. Vui lòng đợi trước khi thử lại.",
    "account_info_not_found": "Không tìm thấy thông tin tài khoản.",
    "account_info_already_created": "Thông tin tài khoản đã được tạo.",
    "id_number_already_in_use": "Số ID đã được sử dụng.",
    "account_info_can_not_update": "Không thể cập nhật thông tin tài khoản.",
    "account_profile_is_processed": "Thông tin cá nhân đang được xử lý.",
    "insufficient_fund": "Không đủ tiền hoặc số dư tín dụng.",
    "account_email_is_exist": "Email đã được đăng ký sử dụng.",
    "proxy_error": "Lỗi kết nối proxy.",
    "invalid_file_type": "Định dạng file không hợp lệ. Vui lòng dùng định dạng hỗ trợ.",
    "file_too_large": "Kích thước file vượt quá giới hạn 20MB.",
    "account_banned": "Tài khoản của bạn đã bị khóa.",
    "login_failed": "Đăng nhập thất bại. Vui lòng kiểm tra lại thông tin.",
    "error_code": "Mã xác thực không hợp lệ.",
    "user_not_found": "Không tìm thấy người dùng.",
    "user_used_invite_code": "Mã giới thiệu đã được sử dụng.",
    "get_me_failed": "Tải thông tin cá nhân thất bại.",
    "user_cannot_use_own_invite_code": "Bạn không thể sử dụng mã giới thiệu của chính mình.",
    "file_not_found": "Không tìm thấy file.",
    "file_upload_failed": "Tải file lên thất bại. Vui lòng thử lại.",
    "upload_webp_failed": "Tải file WEBP lên thất bại.",
    "create_theme_failed": "Tạo chủ đề thất bại.",
    "get_theme_failed": "Không thể lấy thông tin chủ đề.",
    "category_already_exists": "Danh mục đã tồn tại.",
    "create_category_failed": "Tạo danh mục thất bại.",
    "invalid_ratio": "Tỷ lệ video không hợp lệ.",
    "create_media_failed": "Không thể khởi tạo quá trình tạo video.",
    "media_not_found": "Không tìm thấy file video hoặc ảnh.",
    "callback_media_failed": "Xử lý phản hồi media thất bại.",
    "get_media_detail_failed": "Không thể lấy thông tin chi tiết video.",
    "get_media_failed": "Không thể tải danh sách media.",
    "update_theme_failed": "Cập nhật chủ đề thất bại.",
    "delete_theme_failed": "Xóa chủ đề thất bại.",
    "category_not_found": "Không tìm thấy danh mục.",
    "delete_category_failed": "Xóa danh mục thất bại.",
    "media_not_owned": "Bạn không sở hữu tệp tin này.",
    "theme_already_exists": "Chủ đề đã tồn tại.",
    "like_media_failed": "Không thể cập nhật trạng thái yêu thích.",
    "user_not_vip": "Tính năng này yêu cầu đăng ký VIP.",
    "not_enough_credit": "Không đủ tín dụng. Vui lòng mua thêm credit.",
    "create_photo_enhance_failed": "Nâng cấp chất lượng ảnh thất bại.",
    "remove_object_failed": "Xóa vật thể khỏi ảnh thất bại.",
    "get_suggestion_prompt_failed": "Không thể tạo gợi ý mô tả.",
    "get_tasks_failed": "Không thể tải danh sách nhiệm vụ.",
    "action_task_failed": "Thực hiện nhiệm vụ thất bại.",
    "task_not_found": "Không tìm thấy nhiệm vụ.",
    "task_already_claimed": "Phần thưởng nhiệm vụ đã được nhận.",
    "task_already_started": "Nhiệm vụ đã được bắt đầu trước đó.",
    "task_not_completed": "Nhiệm vụ chưa được hoàn thành.",
    "rate_app_failed": "Đánh giá ứng dụng thất bại.",
    "daily_login_task_not_found": "Không tìm thấy nhiệm vụ điểm danh.",
    "get_daily_login_failed": "Tải nhiệm vụ điểm danh thất bại.",
    "today_login_reward_already_claimed": "Phần thưởng điểm danh hôm nay đã được nhận.",
    "take_login_reward_failed": "Nhận phần thưởng điểm danh thất bại.",
    "iap_receipt_already_exists": "Hóa đơn mua hàng đã được đăng ký trước đó.",
    "iap_verify_product_failed": "Xác minh sản phẩm mua hàng thất bại.",
    "iap_product_not_purchased": "Sản phẩm chưa được mua hàng.",
    "iap_product_not_found": "Không tìm thấy sản phẩm mua hàng.",
    "iap_subscription_not_active": "Gói đăng ký hiện không hoạt động.",
    "iap_subscription_already_acknowledged": "Gói đăng ký đã được xác nhận trước đó.",
    "iap_verify_subscription_failed": "Xác minh gói đăng ký thất bại.",
    "refill_subscription_credits_failed": "Nạp lại credit gói đăng ký thất bại.",
    "cancel_subscription_failed": "Hủy gói đăng ký thất bại.",
    "plan_not_found": "Không tìm thấy gói dịch vụ.",
    "transaction_action_failed": "Giao dịch thất bại.",
    "iap_verify_ios_product_failed": "Xác minh mua hàng iOS thất bại.",
    "iap_subscription_invalid_type": "Loại gói đăng ký không hợp lệ.",
    "subscription_not_active_for_refill": "Gói đăng ký không hoạt động để nạp lại credit.",
    "get_price_list_failed": "Không thể tải danh sách giá credit.",
    "iap_receipt_not_found": "Không tìm thấy hóa đơn mua hàng.",
    "iap_subscription_not_found": "Không tìm thấy thông tin gói đăng ký."
}

i18n_dir = "/Users/linhpham/Documents/project-flutter/ai_video_flutter/lib/i18n"

for filename in os.listdir(i18n_dir):
    if filename.endswith(".i18n.json"):
        lang = filename.split(".")[0]
        filepath = os.path.join(i18n_dir, filename)
        
        errors_map = vi_errors if lang == "vi" else en_errors
        
        with open(filepath, "r", encoding="utf-8") as f:
            try:
                data = json.load(f)
            except Exception as e:
                print(f"Error reading {filename}: {e}")
                continue
        
        data["errors"] = errors_map
        
        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        print(f"Added errors namespace to {filename}")
